language: go

go:
  - 1.13.x

before_install:
  - git clone https://github.com/magefile/mage
  - cd mage
  - go run bootstrap.go

install:
  - mage install

script:
  - mage test

after_success:
  - mage coverage