language: go

go:
  - 1.13.x

before_install:
  - curl -sL https://git.io/tusk | bash -s -- -b /usr/local/bin latest

install:
  - tusk install

script:
  - tusk test

after_success:
  - tusk coverage