language: go

go:
  - 1.11.x
  - 1.13.x
  - master

before_install:
  - curl -sL https://git.io/tusk | sudo bash -s -- -b /usr/local/bin latest

install:
  - tusk install

script:
  - tusk test

after_success:
  - tusk coverage